# CircleCI Firebase Deployment Config
version: 2.1

commands:
  install_dependencies:
    description: 'Install project dependencies'
    parameters:
      directory:
        type: string
        default: ''
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific yarn.lock
            - v1-yarn-<< parameters.directory >>deps-{{ checksum "yarn.lock" }}
            # Fallback cache to be used
            - v1-yarn-deps-
      - run:
          name: Install Dependencies
          command: yarn --cwd ./<< parameters.directory >> install
      - save_cache:
          key: v1-yarn-<< parameters.directory >>deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  check-changed-files-or-halt:
    parameters:
      path:
        type: string
    steps:
      - run: FOLDER=<< parameters.path >> sh check-files.sh

jobs:
  configure_firebase:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: |
            mkdir firebase-tools
            yarn --cwd firebase-tools add -D firebase-tools
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Set up env
          command: |
            pwd
            ls
            firebase-tools/node_modules/.bin/firebase use pub-finder --token $FIREBASE_DEPLOY_TOKEN
            firebase-tools/node_modules/.bin/firebase functions:config:unset env --token "$FIREBASE_DEPLOY_TOKEN"
            firebase-tools/node_modules/.bin/firebase functions:config:set env.google.key="$GOOGLE_API_KEY" --token "$FIREBASE_DEPLOY_TOKEN"
            firebase-tools/node_modules/.bin/firebase functions:config:set env.google.maps_uri="$GOOGLE_MAPS_URI" --token "$FIREBASE_DEPLOY_TOKEN"
  build_app:
    docker:
      - image: circleci/node:10
    steps:
      - install_dependencies
      - run:
          name: Build App
          command: yarn build

  deploy_app:
    docker:
      - image: circleci/node:10
    steps:
      - install_dependencies
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy To Firebase
          # command: firebase-tools/node_modules/.bin/firebase deploy --only hosting --token "$FIREBASE_DEPLOY_TOKEN"
          command: firebase-tools/node_modules/.bin/firebase apps:list --token "$FIREBASE_DEPLOY_TOKEN"

  test_functions:
    # working_directory: ~/project/functions
    docker:
      - image: circleci/node:10
    steps:
      - install_dependencies:
          directory: functions
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Test functions
          command: yarn test-functions

  deploy_functions:
    # working_directory: ~/project/functions
    docker:
      - image: circleci/node:10
    steps:
      - install_dependencies:
          directory: functions
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy functions
          # command: firebase-tools/node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_DEPLOY_TOKEN"
          command: firebase-tools/node_modules/.bin/firebase apps:list --token "$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - configure_firebase
      - build_app
      - test_functions
      - deploy_app:
          requires:
            - configure_firebase
            - build_app
      - deploy_functions:
          requires:
            - configure_firebase
            - test_functions
          # filters:
          #   branches:
          #     only: master
