# CircleCI Firebase Deployment Config
version: 2.1

commands:
  install_dependencies:
    description: 'Install project dependencies'
    parameters:
      directory:
        type: string
        default: ''
    steps:
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific yarn.lock
            - v1-yarn-<< parameters.directory >>deps-{{ checksum "yarn.lock" }}
            # Fallback cache to be used
            - v1-yarn-deps-
      - run:
          name: Install Dependencies
          command: yarn --cwd ./<< parameters.directory >> install
      - save_cache:
          key: v1-yarn-<< parameters.directory >>deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  configure_firebase:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: |
            mkdir firebase-tools
            yarn add -D firebase-tools
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Set up env
          command: |
            ./node_modules/.bin/firebase functions:config:unset env --token "$FIREBASE_DEPLOY_TOKEN"
            ./node_modules/.bin/firebase functions:config:set env.google.key="$GOOGLE_API_KEY" --token "$FIREBASE_DEPLOY_TOKEN"
            ./node_modules/.bin/firebase functions:config:set env.google.maps_uri="$GOOGLE_MAPS_URI" --token "$FIREBASE_DEPLOY_TOKEN"

  build_app:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build App
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  build_functions:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Check for updates
          command: bash ./scripts/check-functions-commit.sh
      - install_dependencies:
          directory: functions
      # - run:
      #     name: Lint functions
      #     command: yarn --cwd functions run lint
      - run:
          name: Build functions
          command: yarn --cwd functions run build

  test_functions:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Check for updates
          command: bash ./scripts/check-functions-commit.sh
      - install_dependencies:
          directory: functions
      - run:
          name: Test functions
          command: yarn --cwd functions run test-ci

  deploy_app:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - install_dependencies
      - attach_workspace:
          at: .
      - run:
          name: Deploy To Firebase
          command: ./node_modules/.bin/firebase deploy --only hosting --token "$FIREBASE_DEPLOY_TOKEN"

  deploy_functions:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Check for updates
          command: bash ./scripts/check-functions-commit.sh
      - install_dependencies
      - install_dependencies:
          directory: functions
      - run:
          name: Deploy functions
          command: ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - configure_firebase
      - build_functions:
          requires:
            - configure_firebase
      - build_app:
          requires:
            - configure_firebase
      - test_functions:
          requires:
            - build_functions
            - configure_firebase
      - deploy_app:
          requires:
            - build_app
          filters:
            branches:
              only: master
      - deploy_functions:
          requires:
            - configure_firebase
            - build_functions
            - test_functions
          filters:
            branches:
              only: master
