#import "./LocationFragment.gql"
#import "./OpenHoursFragment.gql"

query NearbyPubsQuery($coords: CoordsInput!, $now: String) {
  location(coords: $coords) {
    ...locationDetails
  }
  pubs(coords: $coords) {
    id
    name
    address
    coords {
      lat
      lng
    }
    rating
    priceLevel
    directions {
      distance
      bearing
    }
    photos(size: 800) {
      url
      attribution
    }
    openTimes(now: $now) {
      ...openHours
    }
  }
}
