#import "./LocationFragment.gql"
#import "./OpenHoursFragment.gql"

query NearbyPubsQuery($coords: CoordsInput!) {
  location(coords: $coords) {
    ...locationDetails
  }
  pubs(coords: $coords) {
    name
    address
    coords {
      lat
      lng
    }
    rating
    priceLevel
    distance
    photos(size: 800) {
      url
      attribution
    }
    openTimesToday {
      ...openHours
    }
  }
}
