#import "./LocationFragment.gql"
#import "./OpenHoursFragment.gql"

query NearbyPubsQuery(
  $coords: CoordsInput!
  $first: Int
  $skip: Int
  $now: String
) {
  location(coords: $coords) {
    ...locationDetails
  }
  pubs(coords: $coords, first: $first, skip: $skip) {
    id
    name
    address
    coords {
      lat
      lng
    }
    rating
    priceLevel
    link
    directions(from: $coords) {
      distance
      bearing
      link
    }
    openTimes(date: $now) {
      ...openHours
    }
  }
}
